name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: adnan4772/flutter-android-setup:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Flutter Version
        run: flutter --version

      - name: Print Java Version
        run: java --version

      - name: Print Gradle Version
        run: gradle --version

      - name: Flutter Doctor
        run: flutter doctor -v
