name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the Docker image using the provided Dockerfile
      - name: Build Docker image
        run: docker build -t flutter-android-build .

      # Run the Docker container and execute the build steps
      - name: Run build in Docker
        run: |
          docker run --rm -v $(pwd):/app flutter-android-build bash -c "
            # Print versions
            echo 'Flutter version:'
            flutter --version
            echo 'Java version:'
            java --version
            echo 'Gradle version:'
            gradle --version
            # Run Gradle command to build APK
            gradle app:assembleAndroidTest
          "

      # Store the generated APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-test-apk
          path: app/build/outputs/apk/androidTest/**/*.apk