name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    container:
      image: adnan4772/flutter-android-setup:latest
      options: --platform linux/amd64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Flutter Version
        run: flutter --version

      - name: Print Java Version
        run: java --version

      - name: Print Gradle Version
        run: gradle --version

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Get Flutter Dependencies
        run: flutter pub get